(chore) update alert style
honehealth/jutsu pull request #12
Opened 2024-12-23 16:35 UTC by lvanderbilt

Alert style updated for Error status to improve readability, and updated success to look consistent w the error changes. 

![Screenshot 2024-12-23 at 10 29 03 AM](https://github.com/user-attachments/assets/b17ac584-8d09-4182-b909-d5dc74451acc)
![Screenshot 2024-12-23 at 10 28 45 AM](https://github.com/user-attachments/assets/3d09037e-91fc-44e6-aca1-d33b5701b12d)

2024-12-23 16:56 UTC, wesleynw commented
@lvanderbilt Looks good! There was some discussion on [another PR](https://github.com/honehealth/patient-experience/pull/526#pullrequestreview-2496276964) about alerts style on different pages (eg. sign in, add to cart failure). Does this affect those alerts too/do you have screenshots of those?

2024-12-23 17:10 UTC, dandersonhone submitted a review, later dismissed
Love it—approving but would like to get approval from some of the other engineers too. Did you get this design approved by Michael Hagel?

We will need to update the package.json version for this change so that we can publish to NPM—could you please include that in this PR?

2024-12-24 16:37 UTC, jclark-hone approved these changes

2024-12-24 16:51 UTC, greym0uth requested changes

2024-12-30 14:45 UTC, lvanderbilt commented on src/colors.ts
> +    background: "#ffeaef"
good call, done!

2024-12-30 20:50 UTC, lvanderbilt commented
> Love it—approving but would like to get approval from some of the other engineers too. Did you get this design approved by Michael Hagel?
> 
> We will need to update the package.json version for this change so that we can publish to NPM—could you please include that in this PR?

@dandersonhone no prob, done


> @lvanderbilt Looks good! There was some discussion on [another PR](https://github.com/honehealth/patient-experience/pull/526#pullrequestreview-2496276964) about alerts style on different pages (eg. sign in, add to cart failure). Does this affect those alerts too/do you have screenshots of those?

@wesleynw Yes, this change is global and will effect all toast messaging.  Screenshot of an alert from the sign-in page:

![Screenshot 2024-12-30 at 2 46 32 PM](https://github.com/user-attachments/assets/539b2a3a-9e0c-47ac-8152-d21da43f4582)

2024-12-30 20:54 UTC, wesleynw approved these changes

2025-01-02 20:18 UTC, dandersonhone approved these changes

2025-01-03 17:46 UTC, merged